### ISSUE TITLE
What ontologies are to be included?

### ISSUE THREAD

**Issue by elserj** [Planteome/planteome-core#1]
So far, I am loading the following:
uberon/basic
cl-basic
pato
environment_ontology
plant_ontology
ncbitaxon
trait

I intend to also load GO and ChEBI.

Are there others we need?  Maybe plant disease?  Any we don't need?

**Comment by cooperl09** [comment]
Why are we including Uberon? Also do we need the CL? My understanding is that all the terms specific to plants are in the PO.

**Comment by cooperl09** [comment]
Maybe ENVO will be needed at some point.

**Comment by cmungall** [comment]
correct, cl is largely animal, and uberon is entirely animal.

including ENVO will be confusing because of overlap with eo

Your importer should include:
- po
- eo
- to

But note you will soon move away from the notion of a flat list of ontologies, towards an import graph. You won't specify pato at the top level. You only care about pato because of dependencies in the `to` axiomatization, and that will all be handled by the `to` import.

don't worry, will all make sense soon...

**Comment by cooperl09** [comment]
Thanks Chris!

**Comment by cooperl09** [comment]
We need to be loading ChEBI or at least a slice of it, as the Chebi terms are not displaying properly on the browser: eg. http://browser.planteome.org/amigo/term/CHEBI:62431

**Comment by pbuttigieg** [comment]
> including ENVO will be confusing because of overlap with eo

Perhaps confusing, but if you're interested in the ecosystems relevant to plants or the materials (e.g. soil types) that surround them, it may be worth exploring.

**Comment by cmungall** [comment]
Definitely part of the plan. The main short term issue would be clashing labels between then two, when the semantics are different.

I'd recommend first axiomatizing EO, making use of ENVO and other ontologies. The general design pattern is that ENVO describes material entities and processes, and EO describes perturbations to those. See https://github.com/cmungall/environmental-conditions/ for design patterns that are applicable to EO.

This will also suggest unambiguous names for EO terms

**Comment by pbuttigieg** [comment]
Coordination here would be great and highly reusable in experimental settings!
