### ISSUE TITLE
PO_dev no longer updating nightly

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#6]
Cron job is no longer working, so have to get @elserj to update it manually.   

Would also be good to have a script to do it manually.  
po_amigo_dev_update.script  no longer works.

**Comment by elserj** [comment]
Fixed it by removing old git repo and replace with fresh git clone.  Not sure if it will work for other users than myself because of permissions, but you can try running the script on palea:
/data/www/plantontology/po_amigo/po_amigo_dev_git_update.sh
to update it yourself.  Cron job should be working again though.

**Comment by cooperl09** [comment]
I got "Permission denied"

**Comment by elserj** [comment]
Made the git folder group writable, should fix the permission issue.  Also changed the loading script to make the folder group writable after updating from git.  Let me know if it still doesn't work for you.
